# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 SrednaBG Contributors
#
# SrednaBG — qa

"""Extract the inline TTS strings from AudioAlertManager.kt into a YAML fixture.

Run from repo root:

    python -m qa.fixtures._extract_tts > qa/fixtures/tts_phrases.yaml

The harness asserts on substrings keyed by event (entry_bg, entry_en,
over_limit_bg, etc). When a phrase changes in the app source, regenerate
this fixture and review the diff in the same PR.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "android" / "app" / "src" / "main" / "kotlin" / "bg" / "srednabg" / "app" / "service" / "AudioAlertManager.kt"

# Lines like:  "Влизате в зона за средна скорост. Ограничение $limit."
PHRASE_RE = re.compile(r'"([^"]+)"')


# Ordered: entry, within, over, recovered, exit. BG returns first, EN second
# inside each `if (lang == "bg") { "BG" } else { "EN" }` block.
KEYS = [
    "entry_bg", "entry_en",
    "within_bg", "within_en",
    "over_bg", "over_en",
    "recovered_bg", "recovered_en",
    "exit_bg", "exit_en",
]


def main() -> int:
    if not SRC.exists():
        print(f"# missing source: {SRC}", file=sys.stderr)
        return 2
    text = SRC.read_text(encoding="utf-8")
    matches = PHRASE_RE.findall(text)
    # Filter to the 10 message strings (skip TAG, locale codes, etc).
    msgs = [m for m in matches if any(s in m for s in (
        "Влизате", "Entering", "Средна", "Average", "Внимание", "Warning",
        "отново в норма", "Back within", "Излизате", "Leaving",
    ))]
    if len(msgs) < 10:
        print(f"# expected ≥10 messages, found {len(msgs)} — source format may have drifted",
              file=sys.stderr)
        for m in msgs:
            print(f"#   {m!r}", file=sys.stderr)
        return 2
    print("# Auto-generated by qa/fixtures/_extract_tts.py — DO NOT EDIT BY HAND.")
    print("# Regenerate after changes to AudioAlertManager.kt.")
    print("# Used as substring assertions by the QA harness.")
    print()
    for key, msg in zip(KEYS, msgs[:10]):
        # Strip Kotlin string interpolation tokens for cleaner substring matches.
        stripped = re.sub(r"\$\w+|\$\{[^}]+\}", "...", msg)
        print(f'{key}: "{stripped}"')
    return 0


if __name__ == "__main__":
    sys.exit(main())
