# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 SrednaBG Contributors
#
# SrednaBG — qa

"""Generate the representative-tier YAML matrix: the 6 hand-picked zones in
`qa/fixtures/representative_zones.yaml` × the 4 settings combos
(`SettingsCombo` S1–S4 in `qa/settings.py`) = 24 scenarios.

Run from the repo root:

    python -m qa.scenarios.representative._generate

Output: qa/scenarios/representative/<zone_id>__<combo_id>.yaml — committed to the
repo so PR reviewers see per-scenario diffs when the hand-picked zone list or the
settings matrix changes (same convention as qa/scenarios/bulk/_generate.py).

Each zone drives at the fixture's `speed_kmh` and asserts only enter + exit +
no in-zone rebound — the representative pass exercises zone detection across the
full settings matrix, not over-limit alerting (that's the edge scenarios' job).
"""

from __future__ import annotations

from pathlib import Path

import yaml

from ... import settings as settings_mod

HERE = Path(__file__).resolve().parent
FIXTURE = HERE.parents[1] / "fixtures" / "representative_zones.yaml"

TEMPLATE = """# Auto-generated by qa/scenarios/representative/_generate.py — DO NOT EDIT BY HAND.
# Re-run after `qa/fixtures/representative_zones.yaml` or the SettingsCombo
# matrix (`qa/settings.py`) changes.
name: {name}
zone_id: {zone_id}
speed_kmh: {speed_kmh}
approach_km: 2.0
exit_km: 1.0
hz: 1.0
compression: 4.0
expect_enter: true
expect_exit: true
forbid_in_zone_rebound: true
settings: {settings}
"""


def main() -> None:
    fixture = yaml.safe_load(FIXTURE.read_text(encoding="utf-8"))
    zones = fixture["zones"]
    combos = settings_mod.ALL_COMBOS

    written = 0
    for z in zones:
        zone_id = z["id"]
        speed_kmh = z.get("speed_kmh", 130)
        for combo in combos:
            out = HERE / f"{zone_id}__{combo.id}.yaml"
            out.write_text(
                TEMPLATE.format(
                    name=f"{zone_id} @ {speed_kmh} km/h [{combo.id}]",
                    zone_id=zone_id,
                    speed_kmh=speed_kmh,
                    settings=combo.id,
                ),
                encoding="utf-8",
            )
            written += 1
    print(f"wrote {written} representative scenarios to {HERE}")


if __name__ == "__main__":
    main()
