#!/usr/bin/env bash
#
# Regenerate the bundled zone data.
#
#   1. Full scrape          -> scrapers/data/zones.json   (the scraper default output)
#   2. Sync the build source -> backend/data/zones.json    (kept byte-identical)
#
# backend/data/zones.json is the SINGLE source of truth both apps bundle at
# build time: iOS via its `Bundled Zones` Run Script phase, Android via the
# `prepareZonesAsset` Gradle task. The staged backend/data/version.json is
# regenerated alongside it (update-zones.sh) so the committed metadata always
# matches the data. (The server-side /api/version is a different file —
# regenerated by the Namecheap cron's `--target-dir` run, not here; neither
# version.json is bundled into the apps.)
#
# Run from anywhere:  bash scrapers/scripts/refresh-zones.sh
set -euo pipefail

scrapers_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$scrapers_dir/.." && pwd)"
bash "$REPO_ROOT/scripts/setup-python.sh" --check || exit 1
PY="$REPO_ROOT/.venv/bin/python"
cd "$scrapers_dir"

"$PY" -m src.output
bash ../backend/scripts/update-zones.sh   # cp -> backend/data/zones.json + regenerate version.json

echo "✓ Refreshed zones.json — scrapers/data/ + backend/data/ in sync. Rebuild the app to re-bundle it."
