#!/usr/bin/env bash
#
# Regenerate the bundled zone data.
#
#   1. Full scrape          -> scrapers/data/zones.json   (the scraper default output)
#   2. Sync the build source -> backend/data/zones.json    (kept byte-identical)
#
# backend/data/zones.json is the SINGLE source of truth both apps bundle at
# build time: iOS via its `Bundled Zones` Run Script phase, Android via the
# `prepareZonesAsset` Gradle task. (The server-side /api/version metadata —
# version.json — is regenerated by the Namecheap cron's `--target-dir` run, not
# here; it isn't bundled into either app.)
#
# Run from anywhere:  bash scrapers/scripts/refresh-zones.sh
set -euo pipefail

scrapers_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$scrapers_dir"

python -m src.output
cp data/zones.json ../backend/data/zones.json

echo "✓ Refreshed zones.json — scrapers/data/ + backend/data/ in sync. Rebuild the app to re-bundle it."
