#!/usr/bin/env bash
# Build the Android-consumable map bundle.
#
# Produces:
#   backend/data/map-bundle/          — unzipped tree staged into APK assets
#     ├── style-light.json            (light variant, {MBTILES_URI} placeholder)
#     ├── style-dark.json             (dark variant, derived from light)
#     ├── sprite.json / sprite.png    (+ @2x variants, referenced by style)
#     ├── fonts/<fontstack>/<range>.pbf (glyphs for every fontstack referenced by style)
#     ├── bulgaria.mbtiles            (shrunk via download-tiles.sh --maxzoom=12)
#     └── version.json                ({"map_hash": "sha256:..."})
#   backend/data/map-bundle.zip       — zipped bundle served at /api/map/bundle.zip
#
# Runtime (Android/iOS) picks style-light.json or style-dark.json based on the
# auto-day/night resolver and the user's Map theme preference, then replaces
# {MBTILES_URI} / {GLYPHS_URI} / {SPRITE_URI} with absolute on-disk paths.
#
# Prerequisites:
#   - tileserver-gl running locally at http://localhost:8070 serving
#     styles/basic-preview (i.e. `docker compose up` in backend/)
#   - backend/tiles/bulgaria.mbtiles already generated by download-tiles.sh
#   - jq, curl, zip, shasum

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/.."
TILES_DIR="$BACKEND_DIR/tiles"
DATA_DIR="$BACKEND_DIR/data"
BUNDLE_DIR="$DATA_DIR/map-bundle"
BUNDLE_ZIP="$DATA_DIR/map-bundle.zip"

STYLE_ID="basic-preview"
TILESERVER_URL="${TILESERVER_URL:-http://localhost:8070}"
MBTILES_SRC="$TILES_DIR/bulgaria.mbtiles"

for cmd in jq curl zip shasum; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: '$cmd' is required but not installed." >&2
        exit 1
    fi
done

if [ ! -f "$MBTILES_SRC" ]; then
    echo "ERROR: $MBTILES_SRC not found. Run download-tiles.sh first." >&2
    exit 1
fi

if ! curl --fail --silent --max-time 3 "$TILESERVER_URL/health" >/dev/null 2>&1 \
    && ! curl --fail --silent --max-time 3 "$TILESERVER_URL/styles/$STYLE_ID/style.json" >/dev/null 2>&1
then
    echo "ERROR: tileserver-gl not reachable at $TILESERVER_URL." >&2
    echo "       Start it with 'docker compose up' from backend/." >&2
    exit 1
fi

rm -rf "$BUNDLE_DIR" "$BUNDLE_ZIP"
mkdir -p "$BUNDLE_DIR/fonts"

echo "Fetching style.json from tileserver-gl..."
RAW_STYLE=$(curl --fail --silent "$TILESERVER_URL/styles/$STYLE_ID/style.json")

# Does upstream style even use sprites? basic-preview doesn't.
HAS_SPRITE=$(echo "$RAW_STYLE" | jq -r 'has("sprite")')

# Rewrite URIs to local/relative form. We overwrite every vector source's
# `tiles`/`url` with a {MBTILES_URI} placeholder that the runtime substitutes
# with the on-disk mbtiles path. Sprite and glyphs go relative; sprite is
# only emitted if the upstream style references one.
echo "Rewriting style.json for local assets (light)..."
echo "$RAW_STYLE" | jq --argjson hasSprite "$HAS_SPRITE" '
    .sources |= with_entries(
        if .value.type == "vector" then
            .value = {type: "vector", url: "{MBTILES_URI}"}
        else . end
    )
    | (if $hasSprite then .sprite = "{SPRITE_URI}" else del(.sprite) end)
    | .glyphs = "{GLYPHS_URI}/{fontstack}/{range}.pbf"
' > "$BUNDLE_DIR/style-light.json"

# Derive the dark companion. Same schema/sources/layers, only colors differ.
echo "Deriving dark variant (style-dark.json)..."
python3 "$SCRIPT_DIR/derive-dark-style.py" \
    --in "$BUNDLE_DIR/style-light.json" \
    --out "$BUNDLE_DIR/style-dark.json"

# Sprites (only if upstream style declared them)
if [ "$HAS_SPRITE" = "true" ]; then
    echo "Fetching sprite assets..."
    for variant in "" "@2x"; do
        for ext in json png; do
            url="$TILESERVER_URL/styles/$STYLE_ID/sprite${variant}.${ext}"
            dest="$BUNDLE_DIR/sprite${variant}.${ext}"
            if curl --fail --silent --output "$dest" "$url"; then
                :
            else
                rm -f "$dest"
                # 2x variants are optional
                if [ -z "$variant" ]; then
                    echo "ERROR: missing required sprite asset at $url" >&2
                    exit 1
                fi
            fi
        done
    done
else
    echo "Upstream style has no sprite declaration — skipping sprite fetch."
fi

# Glyphs: discover every fontstack referenced by any symbol layer in the style.
# (Portable bash 3.2 — macOS default — so no `mapfile`.)
echo "Collecting referenced fontstacks..."
FONTSTACKS=()
while IFS= read -r line; do
    FONTSTACKS+=("$line")
done < <(
    jq -r '
        [.layers[]?
            | select(.type == "symbol")
            | .layout["text-font"]? // empty
            | if type == "array" then (map(select(type == "string")) | join(",")) else . end
        ] | unique | .[]
    ' "$BUNDLE_DIR/style-light.json"
)

if [ ${#FONTSTACKS[@]} -eq 0 ]; then
    echo "WARNING: no fontstacks found in style — labels will not render." >&2
fi

# Pull every PBF range (0..65535 step 256, so ranges 0-255, 256-511, ...). We
# download all 256 ranges per fontstack but skip 404s; tileserver-gl returns
# 404 for empty ranges which is fine.
echo "Fetching glyph PBFs (this can take a minute)..."
for fontstack in "${FONTSTACKS[@]}"; do
    encoded=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=','))" "$fontstack")
    mkdir -p "$BUNDLE_DIR/fonts/$fontstack"
    for start in $(seq 0 256 65280); do
        end=$((start + 255))
        range="${start}-${end}"
        url="$TILESERVER_URL/fonts/${encoded}/${range}.pbf"
        dest="$BUNDLE_DIR/fonts/$fontstack/${range}.pbf"
        http_code=$(curl --silent --output "$dest" --write-out "%{http_code}" "$url") || true
        if [ "$http_code" != "200" ]; then
            rm -f "$dest"
        fi
    done
done

# Copy the shrunk mbtiles
echo "Copying bulgaria.mbtiles..."
cp "$MBTILES_SRC" "$BUNDLE_DIR/bulgaria.mbtiles"

# Compute bundle hash — sha256 of the sorted file manifest's contents
echo "Computing bundle hash..."
BUNDLE_HASH=$(cd "$BUNDLE_DIR" && find . -type f ! -name version.json -print0 \
    | sort -z \
    | xargs -0 shasum -a 256 \
    | shasum -a 256 \
    | awk '{print $1}')
BUNDLE_HASH="sha256:$BUNDLE_HASH"
BUNDLE_VERSION=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$BUNDLE_DIR/version.json" <<EOF
{
  "version": "$BUNDLE_VERSION",
  "map_hash": "$BUNDLE_HASH"
}
EOF

# Zip for distribution
echo "Zipping bundle..."
(cd "$BUNDLE_DIR" && zip -r -q "$BUNDLE_ZIP" .)

# Patch the server's /api/version endpoint if it exists
VERSION_FILE="$DATA_DIR/version.json"
if [ -f "$VERSION_FILE" ]; then
    echo "Updating $VERSION_FILE with map_hash..."
    tmp=$(mktemp)
    jq --arg h "$BUNDLE_HASH" '.map_hash = $h' "$VERSION_FILE" > "$tmp"
    mv "$tmp" "$VERSION_FILE"
fi

BUNDLE_SIZE=$(ls -lh "$BUNDLE_ZIP" | awk '{print $5}')
echo ""
echo "Done."
echo "  Bundle dir: $BUNDLE_DIR"
echo "  Bundle zip: $BUNDLE_ZIP ($BUNDLE_SIZE)"
echo "  Hash:       $BUNDLE_HASH"
