# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 SrednaBG Contributors
#
# SrednaBG — qa

"""Generate one YAML scenario per zone in scrapers/data/zones.json.

Run from the repo root:

    python -m qa.scenarios.bulk._generate

Output: qa/scenarios/bulk/<zone_id>.yaml — committed to the repo so PR
reviewers see per-zone diffs when the zone catalog changes.

Speed defaults to min(140, vehicle_car_limit + 10) so the assertion
catches over-limit detection on routes whose limit is below the
default 130. This keeps the bulk pass exercising the over-limit branch
on enough zones to catch regressions.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
ZONES_JSON = REPO_ROOT / "scrapers" / "data" / "zones.json"
OUT_DIR = Path(__file__).resolve().parent

TEMPLATE = """# Auto-generated by qa/scenarios/bulk/_generate.py — DO NOT EDIT BY HAND.
# Re-run after `scrapers/data/zones.json` changes.
name: {name}
zone_id: {zone_id}
speed_kmh: {speed_kmh}
approach_km: 2.0
exit_km: 1.0
hz: 1.0
compression: 4.0
expect_enter: true
expect_exit: true
forbid_in_zone_rebound: true
"""


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    data = json.loads(ZONES_JSON.read_text(encoding="utf-8"))
    zones = data["zones"]

    written = 0
    for z in zones:
        zone_id = z["id"]
        car_limit = z.get("speed_limits", {}).get("car", 130)
        # Pick a speed that is plausibly drivable AND likely to produce
        # an in-limit average (keeps the bulk pass focused on detection
        # correctness, not on alerting).
        speed_kmh = min(car_limit + 5, 140)
        out = OUT_DIR / f"{zone_id}.yaml"
        out.write_text(
            TEMPLATE.format(
                name=f"{zone_id} @ {speed_kmh} km/h",
                zone_id=zone_id,
                speed_kmh=speed_kmh,
            ),
            encoding="utf-8",
        )
        written += 1
    print(f"wrote {written} bulk scenarios to {OUT_DIR}")


if __name__ == "__main__":
    main()
